require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PullManifestsController do

  # This should return the minimal set of attributes required to create a valid
  # PullManifest. As you add validations to PullManifest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "file" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PullManifestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pull_manifests as @pull_manifests" do
      pull_manifest = PullManifest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pull_manifests).should eq([pull_manifest])
    end
  end

  describe "GET show" do
    it "assigns the requested pull_manifest as @pull_manifest" do
      pull_manifest = PullManifest.create! valid_attributes
      get :show, {:id => pull_manifest.to_param}, valid_session
      assigns(:pull_manifest).should eq(pull_manifest)
    end
  end

  describe "GET new" do
    it "assigns a new pull_manifest as @pull_manifest" do
      get :new, {}, valid_session
      assigns(:pull_manifest).should be_a_new(PullManifest)
    end
  end

  describe "GET edit" do
    it "assigns the requested pull_manifest as @pull_manifest" do
      pull_manifest = PullManifest.create! valid_attributes
      get :edit, {:id => pull_manifest.to_param}, valid_session
      assigns(:pull_manifest).should eq(pull_manifest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PullManifest" do
        expect {
          post :create, {:pull_manifest => valid_attributes}, valid_session
        }.to change(PullManifest, :count).by(1)
      end

      it "assigns a newly created pull_manifest as @pull_manifest" do
        post :create, {:pull_manifest => valid_attributes}, valid_session
        assigns(:pull_manifest).should be_a(PullManifest)
        assigns(:pull_manifest).should be_persisted
      end

      it "redirects to the created pull_manifest" do
        post :create, {:pull_manifest => valid_attributes}, valid_session
        response.should redirect_to(PullManifest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pull_manifest as @pull_manifest" do
        # Trigger the behavior that occurs when invalid params are submitted
        PullManifest.any_instance.stub(:save).and_return(false)
        post :create, {:pull_manifest => { "file" => "invalid value" }}, valid_session
        assigns(:pull_manifest).should be_a_new(PullManifest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PullManifest.any_instance.stub(:save).and_return(false)
        post :create, {:pull_manifest => { "file" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pull_manifest" do
        pull_manifest = PullManifest.create! valid_attributes
        # Assuming there are no other pull_manifests in the database, this
        # specifies that the PullManifest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PullManifest.any_instance.should_receive(:update).with({ "file" => "MyString" })
        put :update, {:id => pull_manifest.to_param, :pull_manifest => { "file" => "MyString" }}, valid_session
      end

      it "assigns the requested pull_manifest as @pull_manifest" do
        pull_manifest = PullManifest.create! valid_attributes
        put :update, {:id => pull_manifest.to_param, :pull_manifest => valid_attributes}, valid_session
        assigns(:pull_manifest).should eq(pull_manifest)
      end

      it "redirects to the pull_manifest" do
        pull_manifest = PullManifest.create! valid_attributes
        put :update, {:id => pull_manifest.to_param, :pull_manifest => valid_attributes}, valid_session
        response.should redirect_to(pull_manifest)
      end
    end

    describe "with invalid params" do
      it "assigns the pull_manifest as @pull_manifest" do
        pull_manifest = PullManifest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PullManifest.any_instance.stub(:save).and_return(false)
        put :update, {:id => pull_manifest.to_param, :pull_manifest => { "file" => "invalid value" }}, valid_session
        assigns(:pull_manifest).should eq(pull_manifest)
      end

      it "re-renders the 'edit' template" do
        pull_manifest = PullManifest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PullManifest.any_instance.stub(:save).and_return(false)
        put :update, {:id => pull_manifest.to_param, :pull_manifest => { "file" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pull_manifest" do
      pull_manifest = PullManifest.create! valid_attributes
      expect {
        delete :destroy, {:id => pull_manifest.to_param}, valid_session
      }.to change(PullManifest, :count).by(-1)
    end

    it "redirects to the pull_manifests list" do
      pull_manifest = PullManifest.create! valid_attributes
      delete :destroy, {:id => pull_manifest.to_param}, valid_session
      response.should redirect_to(pull_manifests_url)
    end
  end

end
